### ISSUE TITLE
Use a Pixelated Icon rather than a Camera for Non-Identifiable Video

### ISSUE THREAD

**Issue by pichot** [Helpful-Places/dtpr#103]
The camera icon is almost equivalent to CCTV, which a Non-Identifiable Video is decidedly not. Rather, we should use a pixelated camera, or something of the sort, to show that it is technically impossible to identify anything with the data collected by this sensor.

**Comment by AsherML** [comment]
Icon replacement developed by Helpful Places and added to the standard, old icon removed
