### ISSUE TITLE
Adding a drone icon to the taxonomy

### ISSUE THREAD

**Issue by katiewilson21** [Helpful-Places/dtpr#209]
Michigan central needs a drone icon for their deployment. There is currently no drone icon in the standard.

**Comment by katiewilson21** [comment]
No existing icon in the UI library (the Google Material Icons that are used for almost all DTPR taxonomy items). How should we choose an icon that suits the taxonomy?

**Comment by AsherML** [comment]
Added a customized drone item with consultation with project stakeholders
